### ISSUE TITLE
clangd.llvm.org hijacked

### ISSUE THREAD

**Issue by kljohann** [llvm/clangd-www#17]
I just noticed https://clangd.llvm.org is no longer linked to this repo. Apparently someone set up a another repo on GitHub (`daemonsec/llvm`) with the same `CNAME` and was able to hijack the domain this way.

**Comment by sam-mccall** [comment]
Thanks! It seems to have been restored now. Not sure what happened there, but I'll file a report with github.
Looks like someone demonstrating a security vulnerability...

**Comment by sam-mccall** [comment]
Ah, looks like @asl fixed it, thanks Anton!
and also updated the CNAME so it's locked to the llvm account now.

**Comment by asl** [comment]
I've already provided all info on #clangd. Talk to me for more information. No need to file a GH report – I already did this :)
