### ISSUE TITLE
Incorrect default rename option

### ISSUE THREAD

**Issue by njames93** [llvm/clangd-www#20]
Since the release of clangd-11 the default behaviour of rename is to enable cross file renames, yet the documentation still states the feature needs enabled via the command line flag.

**Comment by njames93** [comment]
Just noticed there is the closed 11-rename branch, but thats stale.

**Comment by hokein** [comment]
yeah, I had a PR #8 for that, but it was closed.

**Comment by njames93** [comment]
Just noticed https://reviews.llvm.org/D96495, Guess I'f that lands, We'd need to update the documentation again anyway.

**Comment by sam-mccall** [comment]
Not sure what happened with the PR.
The docs now are accurate (though no longer describe the details of the pre-11 behavior)
