### ISSUE TITLE
Create FAQ

### ISSUE THREAD

**Issue by kirillbobyrev** [llvm/clangd-www#33]
## Candidate Qs

- Why does clangd not show _all_ references?
- How do I stop clangd from indexing certain folders?
- How do I install latest clangd?

**Comment by gislan** [comment]
* Bug says fixed, but I still see the problem - explain how to check the version you are using and link to the "How do I install latest clangd" FAQ entry and "how to build from source" on clang website.

**Comment by GavinRay97** [comment]
- Many people I've talked to about `clangd` seem confused about the fact `clangd`'s flags is just for the language server and not for compiling.
	- IE, my `compile_commands.json` can contain MSVC `cl.exe` commands, but I use `clang` flags in `.clangd` JUST for the sake of parsing/compiling the TU's for analysis.
	- This should be made more obvious or understandable I guess.
- How to fully setup VS Code with `clangd` and `CMake Tools` + `CMakeLists.txt` for development
- How to ignore directories (maybe same as your second point, IE use `CompilerFlags.Add: -isystem`)
- MSVC/Visual Studio apparently have a file called `cpp.hint`, which contains macro definitions needed to parse a project correctly.
	- This ability can be emulated in `clang`/`clangd` and is necessary sometimes:
		- You use `CompileFlags.add: "-imacros'./cpp.hint'"`
 	- https://docs.microsoft.com/en-us/cpp/build/reference/hint-files?view=msvc-160
- How to set up the remote indexer if you work at a large org w/ a big codebase
	- From the org standpoint, running and hosting the indexer
	- From the dev standpoint, how to configure VS Code/`clangd` binary to use the indexer (IE local project-scoped `.vscode/settings.json`)
- How to view C/C++ AST with VS Code
- _(Not really a question, but the fact that `clangd` has `clang-tidy` support built in should maybe be advertised more. I see most people using both `.clang-tidy` and `.clangd` files and they don't know that it's now included -- with much nicer config syntax in `.clangd` 😃)_

**Comment by kirillbobyrev** [comment]
@GavinRay97 wow, such a comprehensive answer, thank you very much!

**Comment by esthermations** [comment]
I see a lot of newbies asking questions that are all solveable by setting up .clangd properly -- the .clangd syntax itself is documented on the website but it's not exactly clear to new folks how to get started with it.

These are the common questions I see:
* How do I tell clangd where to find my headers?
* Where should I put my .clangd file?
* What should my .clangd file even look like?
* I think I set up my .clangd properly, but it's not working. How do I figure out what's wrong?

I think an example .clangd file showing really common options would be quite helpful -- twice I've just pointed people to a simple one I wrote and they figured the rest out from looking at it.

**Comment by HighCommander4** [comment]
Two questions that come up on Discord and Discourse over and over again:

  * Q: How do I get clangd to use my `compile_commands.json` to infer a command for headers outside of my project directory?
    * A: Use the `--compile-commands-dir` command-line option, or the `CompilationDatabase` key in `.clangd`.
  * Q: Clangd picked the wrong source file from `compile_commands.json` to infer a command for my header (i.e. a source file that doesn't actually include the header, and whose command is missing something that's important for parsing the header correctly).
    * A: Known issue, see https://github.com/clangd/clangd/issues/123. A possible workaround is to use [CompDB](CompDB).

**Comment by HighCommander4** [comment]
Another common question:

 * Q: Why is clangd not showing me a diagnostic that's coming from the instantiation of a template defined in a header?
   * A: This is a known limitation motivated by performance, see https://github.com/clangd/clangd/issues/137.

**Comment by HighCommander4** [comment]
Here's another one that comes up repeatedly:

Q: I specified all my compile flags using `CompileFlags: Add:` in `.clangd`. Why are they not taking effect?
A: `CompileFlags: Add:` is meant to be used to tweak commands from `compile_commands.json`, not as a replacement for `compile_commands.json`. You need to have commands in `compile_commands.json` for `CompileFlags: Add:` to apply to them.

**Comment by kadircet** [comment]
> Here's another one that comes up repeatedly:
> 
> Q: I specified all my compile flags using `CompileFlags: Add:` in `.clangd`. Why are they not taking effect?
> A: `CompileFlags: Add:` is meant to be used to tweak commands from `compile_commands.json`, not as a replacement for `compile_commands.json`. You need to have commands in `compile_commands.json` for `CompileFlags: Add:` to apply to them.

Wait what?? I think that should actually be working (and is the case with me, in the absence of compile_flags.txt and compile_commands.json, the fallback flags are just augmented with any flags coming accumulated through config providers). Can you provide a repro case?

---

As for a general note on this issue itself; I think we should close this as https://clangd.llvm.org/faq exists. People should either open new issues (to discuss the usefulness of different questions), or (preferably) send PRs to extend the list (and we'll have the discussions there). Hence closing the issue, everybody please feel free to re-open if you think otherwise.

**Comment by HighCommander4** [comment]
> > Here's another one that comes up repeatedly:
> > Q: I specified all my compile flags using `CompileFlags: Add:` in `.clangd`. Why are they not taking effect?
> > A: `CompileFlags: Add:` is meant to be used to tweak commands from `compile_commands.json`, not as a replacement for `compile_commands.json`. You need to have commands in `compile_commands.json` for `CompileFlags: Add:` to apply to them.
> 
> Wait what?? I think that should actually be working (and is the case with me, in the absence of compile_flags.txt and compile_commands.json, the fallback flags are just augmented with any flags coming accumulated through config providers). Can you provide a repro case?

You're right, it looks like I was mistaken about this. I'm not sure why I remembered this not working, but it does work now.

> As for a general note on this issue itself; I think we should close this as https://clangd.llvm.org/faq exists. People should either open new issues (to discuss the usefulness of different questions), or (preferably) send PRs to extend the list (and we'll have the discussions there). Hence closing the issue, everybody please feel free to re-open if you think otherwise.

Sounds good. I'll go through the questions I suggested in this issue and send PRs for them.
