### ISSUE TITLE
Link from "Configuration" to "remote-index.md" is broken

### ISSUE THREAD

**Issue by i-ky** [llvm/clangd-www#63]
https://github.com/llvm/clangd-www/blob/b8cca6c16d63c78487c7cafa18ab67e202e927c1/config.md?plain=1#L175 Likely broken by #36 which moved `remote-index.md` to `design/`. But I guess nowadays after a29a247e55bcd7de868c9ffdee710dc0ca2b388f the link should point to `guides/remote-index`.

I would also suggest to change the page redirections land on. Currently it is `design/remote-index` https://github.com/llvm/clangd-www/blob/a29a247e55bcd7de868c9ffdee710dc0ca2b388f/design/remote-index.md?plain=1#L2-L3 but it should probably be more user-oriented `guides/remote-index`. Perhaps, this change will require changing the following link https://github.com/llvm/clangd-www/blob/a29c3179b51400d7dabfcf95c9d079605533ad73/design/indexing.md?plain=1#L94 to `design/remote-index`.

I can submit a PR once we agree on the scope of changes.

**Comment by kadircet** [comment]
thanks for noticing and taking a look at this (and sorry for the long turnaround).

your proposals on changing the redirections LGTM. i'll also approve #64.

**Comment by i-ky** [comment]
No worries, thank you for having a look!

I've filed #65 with redirection changes.
