### ISSUE TITLE
Add a section about the coc-clangd client

### ISSUE THREAD

**Issue by HighCommander4** [llvm/clangd-www#90]
We have an [Editor plugins](https://clangd.llvm.org/installation#editor-plugins) section which covers how to set up clangd, and some important workflows like how to get logs or how to specify command-line arguments, for some popular clients.

For vim, we have a section about two plugins: [YouCompleteMe](https://ycm-core.github.io/YouCompleteMe/) and [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim).

However, another popular vim plugin seems to be [coc-clangd](https://github.com/clangd/coc-clangd). (And it's even somewhat official, given that its repo lives in the clangd org?)

It would be nice to add a section for coc-clangd as well.

**Comment by HighCommander4** [comment]
cc @fannheyward, maybe you would be interested in this? :smile:

**Comment by fannheyward** [comment]
I'm glad to improve this.

**Comment by HighCommander4** [comment]
@fannheyward friendly ping :)

Today there was a user in the clangd Discord channel who didn't know how to get clangd logs from coc-clangd, and I also didn't know what to tell them.

**Comment by HighCommander4** [comment]
I came across information about how to specify command-line arguments in the coc-clangd repo's README: https://github.com/clangd/coc-clangd?tab=readme-ov-file#configurations
